### ISSUE TITLE
Add Casks to search

### ISSUE THREAD

**Issue by adidalal** [Homebrew/braumeister#117]
We at caskroom have a very simple version of a web-based search up at https://caskroom.github.io/search.

This looks significantly nicer, and fairly useful. Would it be possible to add caskroom/homebrew-{cask,fonts,drivers,versions,eid} to the "browse specific taps" section?

Happy to make the PR, but don't see the list of taps that show up there in the codebase (looks like it's in the db).

We do have the relevant info, ie.
```bash
[~] > brew cask info docker
docker: 18.03.0-ce-mac60,23751
https://www.docker.com/community-edition
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/docker.rb
==> Names
Docker Community Edition
Docker CE
==> Artifacts
Docker.app (App)
```

**Comment by MikeMcQuaid** [comment]
This would be more involved than just a search but having to make the entire site support Casks. Personally I'm also 👎 on having more than one tap in here; consolidation would be more consistent with Homebrew itself.

**Comment by adidalal** [comment]
Not a problem, thanks for the prompt reply!

**Comment by MikeMcQuaid** [comment]
Will let @koraktor chip in first!

**Comment by koraktor** [comment]
I’m not really up-to-date on the current status of casks. How are they affiliated with Homebrew (in sense of organization and code base)?

When I had a look at this a few years back I quickly dropped the idea because it essentially meant building a second application. I don’t know if this changed by now.

Apart from that, something like `casks.brew.sh` might be something to consider even if (optimally) this is the application.

**Comment by adidalal** [comment]
The codebase for Homebrew-Cask is a part of Homebrew now.
Casks and Formulas don't look the same, however.  `brew cask info {{cask_name}}` does give you all the necessary details about a cask, and there's also `brew cask _stanza {{stanza_name}} {{cask_name}}` for specific bits.

Organization-wise, we're still separate. See https://github.com/caskroom/homebrew-cask/issues/41990

**Comment by MikeMcQuaid** [comment]
Moved to https://github.com/Homebrew/formulae.brew.sh/issues/13
