### ISSUE TITLE
Display Homebrew analytics data

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/braumeister#52]
Make use of the command or code of https://github.com/homebrew/homebrew-formula-analytics to query Homebrew's analytics data and display that on each formula's page. I can provide you with a token that will get you access to query this data on your Heroku servers.

**Comment by koraktor** [comment]
Sounds amazing. Thanks.

Do you have some example data so I can experiment a bit?

**Comment by MikeMcQuaid** [comment]
@koraktor Sure thing. I'll send you an invite to our Slack.

**Comment by MikeMcQuaid** [comment]
Moved to https://github.com/Homebrew/formulae.brew.sh/issues/10
