### ISSUE TITLE
Separate mandatory/optional dependencies

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/braumeister#57]
As-is this leads to a bit of user confusion: https://discourse.brew.sh/t/ffmpeg-dependencies/1124

**Comment by koraktor** [comment]
This could be achieved by mapping the `build_dependencies` and `optional_dependencies` attributes of the formula JSON data to individual associations in `Formula`.

**Comment by MikeMcQuaid** [comment]
Moved to https://github.com/Homebrew/formulae.brew.sh/issues/11
