### ISSUE TITLE
Consider Using Algolia for Search

### ISSUE THREAD

**Issue by knpwrs** [Homebrew/braumeister#72]
[https://yarnpkg.com/en/](Yarn) is a package manager for node that uses [Algolia](https://www.algolia.com/) for search. I think it would be great to replicate that experience for homebrew users. Go ahead and try out the search to see what I'm talking about. You just type and results against all of the packages on npm are delivered instantly with no noticeable lag.

[Algolia is free for open source](https://www.algolia.com/for-open-source), for what it's worth.

**Comment by koraktor** [comment]
I don’t see a huge benefit here, but am open to suggestions.
Given the limited data for formulae there’s probably nothing we can’t achieve with tools we already have. Maybe it would require a bit more work, but not impossible.

**Comment by MikeMcQuaid** [comment]
My take on such things: if @knpwrs is offering to create a PR for this: sounds interesting. Otherwise: 👎

**Comment by knpwrs** [comment]
I'd be happy to put something together, but I'd probably need someone who is a member of the Homebrew organization to apply for the open source license after I complete work using the free version of Algolia.

**Comment by MikeMcQuaid** [comment]
@knpwrs If @koraktor is 👍 on that I am too.

**Comment by koraktor** [comment]
@knpwrs Sure. Go ahead and let’s see what’s possible.

**Comment by iam4x** [comment]
Hi! If you need anything from Algolia, just ping me 👍 

I had this idea as shower thoughts this morning, would be happy to help @knpwrs :)

**Comment by pixelastic** [comment]
Tim from Algolia here, working with @iam4x. This is a terrific idea and I would also be happy to help in any way I can :)

**Comment by MikeMcQuaid** [comment]
Moved to https://github.com/Homebrew/formulae.brew.sh/issues/12
